/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 29d6f04acc6982d1cd7f4b4f5761cf54)
interface __BaseEnv_Env {
	COUNTERS: DurableObjectNamespace<import("./src/worker").CounterObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "CounterObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
